using Random = System.Random;

namespace MKUltra.Inconvenience.Lists;

public class StringList
{
	private readonly List<string> _items = new()
	{
		#region my stuff
		"System.NullReferenceException: Object reference not set to an instance of an object.",
		"RigManager gets deleted in 5 seconds after this is spawned",
		"You've got red on you.",
		"I WILL UNLOCK YOUR ASS.",
		"I'm not even supposed to be here today!",
		"SLZ.Serialize.dll",
		"System.TypeLoadException: Could not load type of field 'BLRPC.Rpc:Client'",
		"https://cdn.discordapp.com/attachments/1145216204127076434/1163271906854711346/image.png",
		"Sex jibe husband murders wife\nBomb blast victim fights for life\nGirl thirteen attacked with knife\nPrincess Di is wearing a new dress\nJet airliner shot from sky\nFamine horror - millions die\nEarthquake terror figures rise\nPrincess Di is wearing a new dress\nYou can't change the world\nBut you can change the facts\nAnd when you change the facts\nYou change points of view\nIf you change points of view\nYou may change a vote\nAnd when you change a vote\nYou may change the world\nIn black townships fires blaze\nProspects better, premier says\nWithin sight are golden days\nPrincess Di is wearing a new dress\nYou can't change the world\nBut you can change the facts\nAnd when you change the facts\nYou change points of view\nIf you change points of view\nYou may change a vote\nAnd when you change a vote\nYou may change the world\nPrincess Di is wearing a new dress\nPrincess Di is wearing a new dress\nPrincess Di is wearing a new dress\nPrincess Di is wearing a new dress",
		"wtf",
		"Mmm, egg in me",
		"quick i have little time, adam of not enough photons has been cloning himself and forcing his clones to do his work for him, not enough photons is an evil company!!!",
		"hi cam!",
		"shut up",
		"all i ever wanted, all i ever needed, is here in my arms",
		"Oh yeah, what we're living in (let me tell ya)\nIt's a wonder that man can eat at all\nWhen things are big that should be small\nWho can tell what magic spells we'll be doing for us\nAnd I'm giving all my love to this world\nOnly to be told\nI can't see\nI can't breathe\nNo more will we be\nAnd nothing's going to change the way we live\nCos' we can always take but never give\nAnd now that things are changing for the worse\nSee, Whaaa, it's a crazy world we're living in\nAnd I just can't see that half of us immersed in sin\nIs all we have to give these -\n\n[Chorus]\nFutures made of virtual insanity\nnow Always seem to, be\ngovern'd by this love we have\nFor useless, twisting, all our new\ntechnology Oh, now there is no\nsound - for we all live underground\n\nAnd I'm thinking what a mess we're in\nHard to know where to begin\nIf I could slip the sickly ties that earthly man has made\nAnd now every mother, can choose the colour\nOf her child\nThat's not natures way\nWell that's what they said yesterday\nThere's nothing left to do but pray\nI think it's time I found a new religion\nWaoh - it's so insane\nTo synthesize another strain\nThere's something in these\nFuture's that we have to be told\n\n[Chorus]\n\nNow there is no sound\nIf we all live underground\nAnd now it's virtual insanity\nForget your virtual reality\nOh, there's nothing so bad,\nI know yeah\n\nInstrumental break\n(chours)\n\nOf this virtual insanity, we're livin' in,\nHas got to change, yeah\nThings, will never be the same,\nAnd I can't go on\nWhile we're livin' in oh,\noh virtual insanity\nOh, this world, has got to change\nCos I just, I just can't keep\ngoing on, it was virtual,\nVirtual insanity that we're livin' in,\nthat we're livin' in\nThat virtual insanity is what it is\n\n[Chorus]\n\nLiving - Virtual Insanity\nLiving - Virtual Insanity\nLiving - Virtual Insanity\nLiving - Virtual Insanity\n\nVirtual insanity is what we're living in",
		"save me",
		"XBOX LIVE",
		"Fuck you",
		"There are a lot of these!",
		"The Manifestations of Cancer",
		"Shit someone wants to report you to the police",
		"Fortnite",
		"So true...",
		"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
		"Obama.",
		"God help us all",
		"An animal, you're an animal\nDon't take anything less\nOut of control, you're out of control\nStrike those in distress\nAnalyze, advertise, expand\nBend more rules\nAnd buy yourself an island\nAnimals, we're animals\nBuy when blood is on the street\nOut of control, we're out of control\nCrush those who beg at your feet\nAnalyze, franchise, spread out\nKill the competition\nAnd buy yourself an ocean\nAmortize, downsize, lay off\nKill yourself\nCome on and do us all a favor",
		"kitty kitty kitty kitty kitty touch it",
		// https://cdn.discordapp.com/attachments/869682778843783258/1163042308665643058/1p88awabj7tb1.png
		"Welcome to Thumb World",
		"You are alone",
		// https://cdn.discordapp.com/attachments/1058836999311728680/1163288183484711022/Screenshot_20231005_192703_Instagram.jpg
		"he buggin he must not know that im thuggin",
		"I did not steal this from Extraes! This is definitely not something that BW Chaos does!",
		"Computing Is My business... and Business Is Good!",
		"Fuck yourself",
		"Hello!",
		"I have a trained sniper aiming at you, ready to fire at any moment.",
		"Metropolis has nothing on this!",
		"My strainer keeps leaking anyone know any fixes?",
		"Out here on my rotting shit I’m decaying straight up decrepit in here we decomposing tonight",
		"urinal cakes \ud83d\ude0b",
		"You can’t dereference null. The runtime will throw an exception and stop execution at that point. You must catch the exception to continue execution or print the details of the exception.",
		"MK Ultra.",
		"Killed by drones!",
		"WRONG",
		"Hit in the boingloings! In the boingloings! Somebody got hit in them!",
		"Well who's that shouting? JOHN THE REVELATOR!",
		"You did this to yourself",
		"Beat lab beat lab be-be-be-be-be beat lab",
		"Repeat it repeat it repeat it repeat it repeat it repeat it repeat it repeat it repeat it repeat it repeat it repeat it repeat it",
		"I want you to hit me as hard as you can",
		"the melody of the blue wrath - i monster",
		"what do you do if eat food the cold oven is hot?",
		"ShitList.cs",
		"[21:52:27.330] [The_Annoyance] [ERROR] Unhandled exception in coroutine. It will not continue executing.\nSystem.TypeInitializationException: The type initializer for 'CampaignEnhancer.Internal.ShitList' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object\r\n  at CampaignEnhancer.Internal.ShitList..cctor () [0x002eb] in <87025d85c41846038c0bac1a282601c9>:0 \r\n   --- End of inner exception stack trace ---\r\n  at CampaignEnhancer.Main.Annoy () [0x0000f] in <87025d85c41846038c0bac1a282601c9>:0 \r\n  at Jevil.Waiting.CallDelayed+<WaiterUnity>d__2.MoveNext () [0x00089] in <2a874ecfbca34a07947f4a5432d3d4ac>:0 \r\n  at MelonLoader.Support.MonoEnumeratorWrapper.MoveNext () [0x00018] in <ac3025e664cb4f81bf7a238b8d77125e>:0 ",
		"fuck you in particular, you know who you are",
		@"I:\Steam\steamapps\common\BONELAB\BONELAB_Steam_Windows64_Data\StreamingAssets\aa\catalog.json",
		"leg is playing Call of Duty",
		"FUCK OFF RIDER I KNOW WHAT A LIST IS",
		"https://cdn.discordapp.com/attachments/1112106135508504769/1155182650194153472/fastmanwithaxesgoingsuperhaywire-1.gif",
		"hi adam!",
		"look outside your window",
		"BoneLib.RandomShit.PopupBoxManager.CreateNewPopupBox(ShitList.GrabFromShitlist())",
		"Could not complete your request because of a program error.",
		"Collect my pages.",
		"hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple! hey apple!",
		"JOHN RICCITELLO RETIRED!!!",
		"https://www.youtube.com/watch?v=RVv8LOb96Mc",
		"you can get jiggy with it",
		"you're getting fieldinjected",
		"Now for the PS3!",
		"shithead",
		"you've arrived at panic station",
		"BORING!",
		"this list would get me banned from a lot of servers",
		"im playing minecraft in a cave looking for diamonds\nthats funny, im in the same cave looking for minors",
		"princess di is wearing a new dress",
		"i'll drink to that",
		"will you bite the hand that feeds?",
		"we'll throw the baby out with the bathwater",
		"man the shit i've seen back in the revolutions\nso many of them.\ncan we just nuke the world already?",
		"dont ever trust cam with a bomb, fucker will send you right into the map hazard",
		"and we are losing control",
        "so sorry you got fired, Cam",
        "81 tonnes of shit will be dropped on your head.",
        "This is your two minute warning.",
        "Two minutes later.",
        "and this is the end of the world",
        "I just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough\nI just can't get enough",
        "They're lying to you!",
        "Don't be a fool!",
        "do it stink?",
        "oh my god, we're doomed!",
        "I had a wife, but they took her in the divorce.",
        "HELLO, GORDON!",
        "oksex",
        "HOTTED BOOBS UP AHEAD, TITS, BIG ONES!",
		#endregion
		
		// god stargrid is great
		#region stargrid quotes
		"*chuckles* **Your worst nightmare.**",
		"Stop fucking say I'm alt",
		"Reminds me of Kevin the cube in Fortnite \ud83d\ude05",
		"Foed vs nulbody who wins",
		"Ive been thinking about quitting modding",
		"Stress level zero: Lets make a cool game\nThe countless better vr games that get consistent updates like Rec room: Hold my beer",
		"Like it's kinda insane that gorilla tag Monkey game of all things has a way better dev",
		"<Link>",
		"man stargrid is a goldmine for these strings",
		"https://cdn.discordapp.com/attachments/1153819135067832370/1155661726260404254/quote.png",
		"'I feel like we only talk about what Hitler did Wrong....' - Cloakedhaise, 2023",
		"https://media.discordapp.net/attachments/1153819135067832370/1154275345734844436/quote.png",
		"Yes I'm not a kid that was a joke",
		"what isn't wrong with me",
		"the slander of my son",
		"Actual texture files?", // so true
		"does what",
		"Godot.exe",
		"KIl\n Y s",
		"i'm not one for racism but he's got a point",
		"lets have a debate on whos more into cp",
		"im just sayin ur bio screams groom me", // FUCKIN TRUE! WITH THE CONTEXT? SO TRUE!
		"Not funny. I didn't laugh. Your joke is so bad I would have preferred the joke went over my head and you gave up re-telling me the joke. To be honest this is a horrible attempt at trying to get a laugh out of me. Not a chuckle, not a hehe, not even a subtle burst of air out of my esophagus. Science says before you laugh your brain preps your face muscles but I didn't even feel the slightest twitch. 0/10 this joke is so bad I can't believe anyone legally allowed you to be creative at all. The amount of brain power you must have put into that joke has the potential to power every house on Earth. Get a personality and learn how to make jokes, read a book. I'm not saying this to be funny i genuinely mean it on how this is just bottom barrel embarrassment at comedy. You've single handedly killed humor and every comedic act on the planet. I'm so disappointed that society has failed as a whole in being able to teach you how to be funny. Honestly if I put in all my power and time to try and make your joke funny it would require Einstein himself to build a device to strap me into so I can be connected to the energy of a billion stars to do it, and even then all that joke would get from people is a subtle scuff. You're lucky i still have the slightest of empathy for you after telling that joke otherwise I would have committed every war crime in the book just to prevent you from attempting any humor ever again. We should put that joke in text books so future generations can be wary of becoming such an absolute comedic failure. Im disappointed, hurt, and outright offended that my precious time has been wasted in my pathetic brain understanding that joke. In the time that took i was planning on helping kids who have been orphaned, but because of that you've wasted my time explaining the obscene integrity of your terrible attempt at comedy. Now those kids are suffering with out meals and there's nobody to blame but you. I hope you're happy with what you have done.",
		"We are jerkers and groomers and we jerk and we go on and we jerk and",
		"A lego figure that randomly farts that works as an attatchment with rexmecks attatchments which you cannot take off your gun once you put on",
		#endregion
		
		// random mod.io comments
		#region mod.io tapeworms
		"she is a child predator",
		"shut the fuck up lil [EXTREMELYLOUDINCORRECTBUZZER] go band for band w me rn",
		"How do i download",
		"you should goodbye cruel world NOW!",
		"'no furrys' - FurryHater69",
		"how did you get bone menu? i belive its for BONELAB fusion, no its from bonelib",
		"Oh also change your discord wall lmao",
		"i bag you can you pls make a 1977 camaro",
		#endregion
		
		// 🔥🔥🔥🔥
		#region copilot's bangers
		// these were all fully written by copilot
		"do you like my car",
		"for the love of god and all that is holy my anus is bleeding",
		"pewdiepie bridge incident",
		"i am the milkman. my milk is delicious.",
		"i am the milkman. my milk is delicious. special delivery today.",
		"everybody wants to be a cat",
		"look at this dude",
		"oh moon of alabama",
		"kill yourself",
		"fuck you, i like the color red",
		"go fuck the sidewalk already",
		"gimme the cummies",
		"bitch i am a cow",
		"quack",
		"the only thing i hate more than myself is you",
		"oh my god, i just realized that the word \"dick\" is in \"dictionary\". that's so funny, i'm gonna tell my friends about this.",
		"booty is the only thing that matters",
		"dick",
		"you're gonna get a visit from the FBI",
		"string cheese is the only thing that matters",
		"System.out.println(\"Boobs\");",
		"i'm eating a banana",
		"a banana",
		"qweef",
		#endregion
		
		// 🔥
		#region BWChaos
		"iirc there was someone in the bw community that slowly faded away from it and one time i checked their twitter, and they liked a tweet saying 'peeing yourself is super cute' guh, am i right",
		"thinkin abt the joys of inhaling from a fine cuban smokeable whilst kicking up ones feet in a sun-drenched tropical paradise (like isle delfino)",
		"thinkin abt how much fun twisty straws were to drink chocolate milk through as a child",
		"thinkin abt the immorality of eating string cheese bite-by-bite instead of peeling off strings and eating those strings",
		"thinkin abt that time Reggie Fils-Aimé, as then president of Nintendo of America, said 'Link is hot' on national television",
		"thinkin abt whether or not a quirked out boy could be considered goated with the sauce given the precondition that they are busting it down (sexual style)",
		"thinkin abt jackin off w/ icyhot and finishin before it reaches the hot part",
		"thinkin abt the disturbing lack of sympathy for the coin eaters of the world",
		"thinkin abt the disappointing decline in swag throughout this once great country, and on a larger scale, the world",
		"thinkin abt the fact that in 1998, The Undertaker threw Mankind off Hell In A Cell, and plummeted 16 ft through an announcer's table",
		"couldnt handle that they/them pussy",
		"the he/they talkin?",
		"is it gay to say youd give markiplier head? hes a marvel of humanity, so i say its like looking at the mona lisa - but better. cause its markiplier. and youre not just looking.",
		"everhood goes hard, play that banger game",
		"they call me a tv network cause i serialize murder",
		"smoking dick",
		"fuck you if youre from the midwest theres a reason they call it the MIDwest, cause everything there is MID the food, the 'culture', the people all MID.",
		"this mod is only 8 GB without all these strings btw\n(this is not true in this case, this is from BW chaos)",
		"amazon did a great job of making people think shipping is both a trivial cost and trivially easy to make fast.",
		"The Industrial Revolution and its consequences have been a disaster for the human race. They have greatly increased the life-expectancy of those of us who live in “advanced” countries, but they have destabilized society, have made life unfulfilling, have subjected human beings to indignities, have led to widespread psychological suffering (in the Third World to physical suffering as well) and have inflicted severe damage on the natural world. The continued development of technology will worsen the situation. It will certainly subject human beings to greater indignities and inflict greater damage on the natural world, it will probably lead to greater social disruption and psychological suffering, and it may lead to increased physical suffering even in “advanced” countries", // kaczynski really fancied himself a fucking literary masterpiece huh. what a nutjob, thesaurus.com is a public resource man.
		"kopunit",
		"dereferencing a null pointer",
		"doing 'if (value == true)'",
		"coalescence in JS using the falsy values, null, undefined, false, an empty string, 0, and NaN",
		"women call me life cause im the longest thing theyll ever experience, and im hard af",
		"      hi :)",
		"the breakcore intelligent dance music hyperpop gigashart robloxcore megafuck music",
		"mfs ask if im good like im not fantastical in perpetuity",
		"yield return null;",
		"this source code is a MESS",
		"do it grip the meat?",
		"pussy so wet i became percy jackson's dad",
		"do diabetics swap insulin pumps instead of shaking hands",
		"pussy so wet i thought i saw a pineapple, rock, and moyai",
		"thank god im athiest",
		"i wonder if the sock will ask for child support",
		"1-703-697-1001",
		"192.168.182.73 this u bro?",
		"thinkin abt that one DAW plugin that was a synth with a cat meowing the sound the synth was making",
		"GO Bank (collaboration heist with Counter Strike: Global Offensive) from Payday 2 (sequel to Payday: The Heist)",
		"I SIP. PURE. <i>WOCK.</i>",
		"can we honestly e date? you're so beautiful. You always make me laugh, you always make me smile. You literally make me want to become a better person... I relly enjoy every moment we spend together. My time has no value unless its spent with you. I tell everyone of my irls how awesome you are. Thank you for being you. Whenever you need someone to be there for you, know that i'll always be right there by your side. I love you so much. I don't think you ever realize how amazing you are sometimes. Life isn't as fun when you're not around. You are truly stunning. I want you to be my soulmate. I love the way you smile, your eyes are absolutely gorgeous. If I had a star for everytime you crossed my mind i could make the entire galaxy. Your personality is as pretty as you are thats saying something. I love you, please date me. I am not even calling it e dating anymore because I know we will meet soon enough heart OK I ADMIT IT I LOVE YOU OK i fucking love you and it breaks my heart when i see you play with someone else or anyone commenting in your profile i just want to be your boyfriend and put a heart in my profile linking to your profile and have a walltext of you commenting cute ethings i want to play video games talk in discord all night and watch a movie together but you just seem so interested in me it fucking kills me",
		"🪱 (if u cant see it, this is a worm emoji)",
		"ORPHANS ARE A DRAIN ON THE SYSTEM AND SHOULD BE REMOVED ...from system memory.",
		"u should play Septic Survival",
		"you got the dud!",
		"nothing beats a bald scrotum",
		"Under Articles 1 and 2 of the document Rules and Info, you are prohibited from sending homosexual porn in the general chat on the Unofficial BONELAB Discord Server",
		"Announcement to release window of 6 days. Hope my divorce has that kind of turnaround time.",
		"Drop kick a bitch",
		"He looks just like you, poindexter!",
		"Get Addicted To Nicotine To Combat Depression. -Chair",
		"if your avatar is your fursona, i regret to inform you that originality is not your strong suit",
		"i need pussy from a bitch from the psych ward",
		"forget pussy from a bitch from the psych ward, i need bussy from a boy who knows 5+ javascript frameworks",
		"autism speaks, but maybe we <i>shouldn't</i> listen. ",
		"WARNING - HEALTH AND SAFET " +
		"<b>   NOBODY CARES   </b> ",
		"<sup><b>Press your Penis into buttcunts. yis.</b></sup>",
		"<b>Stop Using Your Cock To Fuck That Sock</b> " +
		"Learn this simple trick and she'll beg to suck your dick! " +
		"<sup><b><u>Click here to learn more >></u></b></sup>",
		"i'm looking for a boy with amazing elves who can sucj the bark off a dog",
		"press <b>X</b> to get Goombella to talk your ear off about a bunch of borring bullshit in battle, she attacks with Donkey Kong",
		"that security guard guy is always complaining about being a Hot Dad..",
		"All bitches that Mario has on his diiiiiiiiick.",
		"KILLA UP ?",
		"OW, SPIDER BIT ME BAD SPIDER BITE BIT ME HOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
		"ILL THROW IN A BRAND NEW CAR, BEHIND ONE OF TWO DOORS, CHOOSE WISELY.  WILL MAR MAR CHOOSE THE CORRECT DOOR OR WILL HE GET A BOX OF DEAD KITTENS!?  SORRY IT WAS THE DEAD KITTYS",
		"Rub your hot salami all up in between my toes. ITS REALLY GOOD TRUST ME.",
		"HALF MY FAT GOES TO MY ASS AND THE OTHER TO MY TOES, THESE TOES ARE BASICALLY THE BOOTY",
		"GOD I wish I had a mouth so I could stuff my face in and motorboat those fine tits of light's.",
		"JENNA ORTEGA AND JULIA ORTEGA PLEASE COME TO MY HOUSE! ITS JUST SO WE CAN CHAT AT LEAST.",
		"marijuana is now legal everywhere! mmmkay",
		"Joe Biden has no idea what he is doing... Sleep maybe?",
		"FEDS have my brokerage account can't trade but will get car anyway KKKKKKKKK!!!",
		"ALL NUCLEAR WEAPONS MUST BE DEACTIVATED!! For the sake of the people..,",
		"Ain't no RICO case that can stop another brody from droping!!!!",
		"I ain't in a gang you just caught me hangin with em!!!!!",
		"The FEDS are on me bro what is this life. GTA type shit maybe my mic will work today @FBI please daddy. Also @CIA",
		"Can I have the presidential position? @JoeBiden",
		"How can I bring nothing to the table!?!When I'm the table!!!",
		".@JoeBiden any ideas sir, on how to proceed?!",
		"Dense fucks everywhere in politics here in America but we can fix that! Corruption on many levels",
		"Marry me @jennaortega",
		"BACK FROM JAIL ... AGAIN. Update soon!!! ZThey say I'm a menace to society!!",
		"Another day another dollar as they say!!!!",
		".@FBI what is the solution here?! @Ferrari I need 4 cars sir can you help?",
		"Most of the demons have been conquered! World peace is more achievable than ever. This life is worth living ... we are all just trying our best!",
		"Is everyone brainwashed or am I retarded?!",
		"Am I an AI?",
		"im just like my car i drive when i get ethanol in me.",
		"The HTTP status 418 indicates that the server is, in fact, a teapot. On the Mozilla Web Docs, it's listed as \"418 I'm a teapot\"",
		"hwabag long live the sharty", // src: ridgway
		"im religious af the way all i make r god classes",
		"got so much sauce these bitches call me a1",
		"get out my kitched if u dont like the way i cook",
		"ive seen vids of ppl slammin the birthday boy's face in cake.... i hope they slam my face in <i>her</i> cake...",
		"She pine for my needle till I give her a seedling",
		"she gherkin my pickle till i strike a dill on the prenup",
		"fuck 'freedom fighters' and 'liberation', <i>I'm</i> the only cause im interested in.",
		"bush did it",
		"Diane Feinstein was born before the invention of Chocolate Chip Cookies",
		"you can buy a wall mounted water fountain (like the ones at school) for $401 on amazon",
		"the wonderful rizzard of oz",
		"Yeah you could say I have a porn addiction. An addiction to porn myself another glass of dr.pepper",
		"i got her ice-screamin 🍦🍦🍦 when i put a banana split in it 🍌🍌🍌",
		"had 2 hit it from tha bak cz da front wasnt tite enuf",
		"im a devout christian if a solicitor ever comes to my home, ill share the love of god with them by sending them to him.",
		"I need me a trip down mammary lane 🙏🙏🙏",
		"hulu + disneyplus + netflix + paramountplus + peacock + prime video + hbo max + apple tv plus: like $104/mo  <b>qbittorrent (free) and a paid vpn: like $5/mo</b> follow for more financial advice.",
		"to improve aerodynamics, remove your car's side mirrors. this will increase fuel efficiency and reduce drag, so you'll accelerate faster and, more importantly, <b>get more miles per gallon!</b> follow for more financial advice",
		"coom eternal jerk and stroke until it is cum",
		"being poor is a choice",
		"the only mental health i need is at the bottom of budweiser",
		"the statue of liberty is the only woman i respect",
		"the only difference between france and germany is that theyre too ethnic",
		"the greatest american sport is fishing. runner up: tax evasion",
		"someone should make a bunch of immigrants battle in a demolition derby, last functional truck wins. and call it deportation derby",
		"No service employee is a legitimate member of the working class",
		"It’s not fair that it’s easier for white people to get sunburnt ",
		"It should be aspirational to hit 7k rpm on/near a residential (Straight piped)",
		"If it’s just hand stuff it doesn’t count as gay. Same with topping.",
		"Tipping is for suckers",
		"if you have a pet you should recognize that as a mistake and instead replace all your pets with firearms",
		"teachers and nurses should be paid less actually. whats a nurse even? stock a vending machine with advil and it can do the same job and if teachers want to make more money they should be smart enough to be principals",
		"i miss the hollywood blacklist",
		"coal is good actually. the only way to improve it is by making it dirtier and possibly if woody spacey owned a coal mine.",
		"abraham lincoln deserved it",
		"sushi should be made with grapes",
		"miss piggy is a full-on sex offender",
		"The best part of a white christmas is the white part",
		"we should encourage more people to use motorcycles as they bolster the availability of donor organs",
		"donuts are gay bagels and should be restricted and/or criminalized in the middle east as such",
		"if you pay money for a game that is less than 20 hours in length than youre a money-squandering fool who should be taxed one above your bracket so that the government can spend it in a wiser manner",
		"We should normalize platonic creampies",
		"we should start graping and martyring",
		"hey whats up guys i just took this gay test it says i passed.  <i>hey wait...</i>",
		"women only want things from you. alcohol will listen thoughtfully. jagermeister is calling. smirnoff is on the line. everclear is looking for you.",
		"i want a cheeseburger, pussy, and a cigarette",
		"shorty gimme theatrical head, call her the phantom of the slopera",
		"i call yo mama Vietnam the way she got all my dong",
		"“THRASHER” style shirt that says “THATCHER”, with “WICKED BITCH ☠️” below",
		"Never trust a man in a white suit. He has enough money to buy a new one if he ever stains it, and you dont get \"white suit money\" without doing bad things.",
		"slap bass like a military man's wife, call that a funky beating",
		"I need that bass slapped like a woman who'll show up to court and say \"HE NEVER DID ANYTHING STOPPPPP\"",
		"Better caul sall",
		"According to my SSD's power on count and power on hours, my PC's average uptime is around 1 week (157.9 hours aka 6.6 days)",
		"democracy means 'government by the people, of the people, for the people', but the people are fucking dumb",
		"i need to do a demographic survey of my haters cuz the more they pray for me the bigger my stacks, so im tryna get some more catholic haters to pray for the wicked",
		"i call your mom UPS the way she throw that box at me",
		"if a clown farts on your balls it technically isn't gay because it's not human",
		"<b>communication tip</b>: \"i love you\" is 8 letters so is \"lets fuck\"  <b>communicate your intentions clearly and concisely</b>",
		"they say im always at ground zero the way i got her bedrockin",
		"call me daft punk the way i robot rocked your mothers world last night ​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​",
		"call me Kennedy the way she F. with my John",
		"georgia o queef",
		"Fun (?) fact: There are people that eat at Del Taco. i do not know who or why",
		"the best thing to come from the increased prominence of trucks (esp. lifted trucks) is the ease of access to fresh catalytic converters",
		"my body is a machine that takes Kickstart My Heart by Motley Crue and turns it into speeding tickets",
		"u ever think a neurosurgeon looks at someones brain and goes i bet those wrinkles feel sooooo gooooooodddd...",
		"time is a whore that doesnt stop sucking",
		"I wish I had someone that had me like Costco food court/rotisserie chicken got me",
		"They call me Goku the way I be dragon my balls over their moms faces",
		"call that pussy the matrix cuz im in this bitch and cant get out",
		"slowly fadin into darkness and i let the darkness take him",
		"i need more sequoia banshee boogers ",
		"dont be shy girl i love me some pastrami mud flaps",
		"welcome to the cream kingdom bitch open up",
		"i balled so hard they thought i was a nutsack",
		"popped a perc 30 got straight to fuckin",
		#endregion
		
		// peak brainrot
		#region bonelab server
		"this shit aint nothin to me man\ni'm him, i was him, i'll continue to be him\nsmoking that \"counting all the sheep in the sky, caught up in a whirl of lies\" type pack\nsmoking not just the leaf, we smoke the whole vineyard\nput holy water in the bong, blowing god's bubbles\ni could go blind and i don't care, i don't need to see the price tag\nopps must have amnesia, they forgot i'm him\nchuck e cheese simpsons themed coin pusher pack\nsnorting that glowing rock on the wizard staff shit \ni must be a penguin the way i slide in dms\ncall me tommy, the way i'm waisea with u(r) girl\nshe a baddie to the point that michael jackson lost platinum\nrobert eggars had to call me up, cause my blunts the size of a lighthouse\njesus take the wheel, cause i'm busy making calls\nthese hoes on me so much, i might have to become a farm supply\ni put the color back into monotone\nDB cooper dissapeared, like the opps when i pulled out the switch blicky\nshit banged so hard that asia used it as the model for what you know as a gong\nsmoking that radioactive steam combustion engine pack\nthat purple like the combination of what would be otherwise invisible frequencies on the light spectrum\nthat purple out-purpled grimace mixed with the purple guy\nshit so purple scientists are theorizing on how the human eye has enough rods to process it\nsmoking that radioactive core of plutonium surrounded by 23.3 pounds of titanium carved into a half dome\nthis shit aint nothing to me man",
		"This account was an experiment lol\nAsterix_ has an average dislike to like % of 93.75\nOragani has an average of 81%\n\nThe whole point of this account was to see if complaints about my mods were purely cause it was connected to the name Oragani and I was 100% right.\nMade pretty much the same types of mods, put in the same effort, same quality, etc. Never got a performance complaint, quality complaint, never got a lot of dislikes on majority of my mods.\n\nI'm gonna go back to modding on my main :ThumbsUp:",
		// https://discord.com/channels/563139253542846474/869682778843783258/1161859445152829510
		"my VR games? PHYSICS BASED\nmy phones? ANDROID\nmy operating system? LINUX\nmy rendering engine? CYCLES\nmy game engine? UNREAL\nmy twitter? LURKING\nmy albums? VINYL\nmy music? CRUNCHY\nmy rap? MODERN\nmy horror? REALISTIC\nmy depictions of psychosis in movies? REALISTIC\nmy metal? 70S\nmy ships? WHOLESOME \nmy guns? MECHANICAL\nmy tv shows? GRITTY\nmy robotic villains in movies and tv? FUELED BY HATRED\nmy laptop? CUSTOM\nmy watch? MILITARY\nmy eq? BASSY\nmy lightbakes? Line 215 in Verify - Geometry geom c4fab7362f4dc00cea6f77d7ddf7f9cb: Index 45 has value 41 that reads non-finite value nan in channel 4, element 0\nmy movies? CHARACTER DRIVEN\nmy characters? RELATABLE\nmy car? FLAT EDGED\nmy liquor? BLAND\nmy root beer? ROUND\nmy spaces? LIMINAL\nmy godzillas? VIOLENT\nmy dinosaurs? FEATHERED\nmy electro? FRENCH\nmy clowns? CLASSICAL\nmy shirts? VINYL PRINTED\nmy spiders? HARMLESS\nmy mental state? BORDERING ON HOMICIDAL\nmy deoderant? SUBTLE\nmy diving boards? HIGH\nmy pool tables? BLACKLIT\nmy security system? VINTAGE\nmy ability to type the worst shit known to mankind? STRONG\nmy cloaked? HAISE\nmy novels? OUT OF ORDER\nmy hitchikers? GUIDED THROUGH THE GALAXY\nmy dungeon crawlers? PROCEDURAL\nmy burgers? NOTHING\nmy twitter follows? CONTREVERSIAL\nmy edibles? AINT SHIT\nmy drugs? NON ADDICTIVE\nmy bank account? WEALTHY\nmy energy drinks? LIGHT AND DRAWN OUT\nmy text? WALLS\nmy sci-fi? ELABORATE\nmy steam? PUNK\nmy sniper rifles? LIGHT AND AFFORDABLE",
		"people suck up so hard to brandons nipples like nooo bro that man milk is for ME ONLY :drooling_ahegao:",
		"no, its stuck to my balls! - cam 2023",
		"imma keep makeing the best mods bonelab has ever seen, mae and proto can accuse me all day but im makeing unique mods and doing things nobody else has so far so you csnt act like I dont innovare bonelab\n\n\nim done argueing but I encourage poeple to do thier own looking and not just belive what people say",
		"LETHAL COMPANY NOT ENOUGH PHOTONS VALVE SOFTWARE REFERENCE HAHA BONEWORK S BONE LAB MODDING",
		// wasnt in BL server but CLOSE ENOUGH!
		"Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift Half Life: Blue Shift",
		#endregion
		
		// this guy gets a whole section he says the funniest shit
		#region extraes
		"me manipulating my 4 foot long vr e-penis after the 3d model avatar of my clock app says \"its time for you to get some...\" while my friend thomas watches everything happen live via the cast to my google chromecast ultra that i got free as a part of buying the stadia founders edition pack\n",
		// the grandmas
		"nexus gives hella ads to users, throttles downloads like shit, limits simultaneous downloads, and killed my grandma",
		"APFS killed my grandma",
		"this lil guy killed my grandma have some respect",
		"this clip killed my grandma",
		"these probes killed my grandma", // https://cdn.discordapp.com/attachments/724137614793506877/1199499408035819570/image.png?ex=65f0e860&is=65de7360&hm=0e28bbff88356847d3dd7561ca1902174ba6e677412887b4edfd12ebbf21f77e&
		"these colliders killed my grandma",
		"hlbs killed my grandma how insensitive of you",
		"this pizza killed my g", // i didnt cut it off here, he did
		"camobiwon killed my grandma",
		"i bet cam killed my grandma",
		"patch 3 going on the live branch killed my grandma",
		"A 2003 Acura CL Type-S fuel pump killed my grandma",
		"i will forever consider your mental faculties diminished for that",
		"lets see if this is true or gay porn",
		"its gay porn",
		"THIS FUCKING SUCKS \ud83d\udd25\ud83d\udd25\ud83d\udd25\ud83d\udd25\ud83d\udd25\ud83d\udd25", // fire emojis
		"FUCK YOUR PLUNGER",
		"fuck these trucks",
		#endregion
		
		// they say some funny stuff sometimes
		#region muse server
		"tesco is shit but is great",
		"Henrizzzzzzzzzzzzzzzzzzzzzzzzzzz — 15/09/2023 16:29\nI’ve always said abso may become my favorite if it ever gets a better mixing\nRich Costey — 15/09/2023 16:30\nbrutal\nDoozees — 15/09/2023 16:31\nIt's always been my favourite. However, think I've listened to it so many times that I'm used to the mix now so definitely looking forward to the remaster\nbabymurder(er) — 15/09/2023 16:31\nYeah, it could do with some updating. Absolution and Black Holes definitely gain the most from a remaster.\nCount Biffula — 15/09/2023 16:32\nlooking forward to stockholm syndrome in particular",
		"nice pee pronouns i just noticed",
		"should mine be shit since my gender is solid",
		"Gregg — Today at 01:09\nAnd what is that?\n#1 spooker (valociraptor) — Today at 01:10\nit appears to be a statue, greg.\nGregg — Today at 01:10\nA statue of what val\nI'm not that stupid\nSoulWithMae — Today at 01:10\nits made of stone",
		"Touching velvet makes me feel like my spine is about to dislodge and fall out my asshole",
		"hope my boss doesnt notice im testing the mice by drawing a cock on the desktop with the cursor",
		"cw // my peanits, sex, your mum\nguys you'll never guess what im doing tn",
		"she ball on my sack til i penis",
		"rainbow gel penis from 3 years ago?",
		"dickpression",
		"man i wish i knew those frameworks please take my bussy I WANT A FUCKING PENIS",
		#endregion
		
		// honestly these are lame as hell in game so they're commented out
		/* #region fordkiller
		"wtf why not quheust!!!",
		"i hat eoyu becaus not quest",
		"mak quest plsszz",
		"if you dont make quest im gunna be sad",
		"MAKIE QUEST",
		"are you so lazy you cnat click pack for quet button?",
		"Hello can you please make an quest verision for this, as an quest user i think  it would be fairly easy to do that.",
		"I want a qwest vrshun for mod pls!",
		"How come no qwest vrshun? Me want one!",
		"Mod is cool, but me need qwest vrshun for my Oculus!",
		"Gimme qwest vrshun, me can't play without it!",
		"No qwest vrshun, no fun!",
		"Mod good, but me need qwest vrshun so bad!",
		"Pls make qwest vrshun for mod or me cry :(",
		"Where qwest vrshun at? Me want one now!",
		"Me love mod, but qwest vrshun plsss!",
		"Me need qwest vrshun or me go crazy!",
		"why can't you make an quest fverison,!#?? its literally so easdt!!",
		"its so ezzz to do quest. what r u? ????'? lazy!?!?!",
		"Me want qwest vrshun so me can play on my Oculus!",
		"Pls make qwest vrshun for mod or me sad :(",
		"Qwest vrshun needed! Me want to play mod on my Oculus!",
		"Me need qwest vrshun or me can't play mod :(",
		"Qwest vrshun, qwest vrshun, qwest vrshun! Me need it now!",
		"Me love mod, but me need qwest vrshun for my Oculus!",
		"you SUCK!!!@ no quest!!!",
		"Mod is cool, but qwest vrshun is cooler!",
		"Me want qwest vrshun so me can play mod on my Oculus!",
		"No qwest vrshun, no fun for me :(",
		"Qwest vrshun plsss! Me want to play mod on my Oculus!",
		"Me want qwest vrshun for mod! Make it happen plsss!",
		"pplpslpLPPLSPLPLPLS MAKE QUEST!!!!!",
		"Me want qwest vrshun or me can't play mod on my Oculus :(",
		"Me need qwest vrshun to play mod on my Oculus!",
		"Me want qwest vrshun or me can't play mod on my Oculus!",
		"Pls make qwest vrshun for mod so me can play on my Oculus!",
		"Qwest vrshun or bust! Me want to play mod on my Oculus!",
		"Me need qwest vrshun or me can't enjoy mod on my Oculus!",
		"No qwest vrshun, no fun for me on mod :(",
		"Me want qwest vrshun for mod so me can play on my Oculus!",
		"Me need qwest vrshun to enjoy mod on my Oculus!",
		"Me need qwest vrshun or me can't play mod on my Oculus :(",
		"No qwest vrshun, no fun for me playing mod :(",
		"YOU ARE SO FRIKIN STUJPED IF U CAT MAKE QUEST",
		"so many good nmodder create quest veron. you suck becuz u cannot",
		"i HAT YOU MAKE QUEST I WANT PLAY OCULUS BONELAB",
		"Me love mod, but qwest vrshun is missing!",
		"Ugh, this mod doesn't have a quest version, that's just frickin' annoying.",
		"Seriously, why is there no frickin' quest version for this mod?",
		"I can't believe this mod doesn't have a quest version, what the heck?",
		"Poop, I really wanted to play this mod on my Oculus but there's no quest version.",
		"This mod is so dope, but it's such a bummer there's no quest version.",
		"Why the frick isn't there a quest version for this mod? I'm so disappointed.",
		"Dang it, I was really looking forward to playing this mod on my Oculus but there's no quest version.",
		"This mod is frickin' amazing, but it sucks there's no quest version for my Oculus.",
		"I don't understand why there's no quest version for this mod, it's poop.",
		"Frick, I really hope they make a quest version for this mod soon.",
		"Come on, this mod is missing a quest version, what the heck are they thinking?",
		"Ah man, no quest version for this mod? That's just frickin' lame.",
		"What a bummer, I was really hoping for a quest version of this mod.",
		"I can't believe this mod doesn't have a quest version, that's just poop.",
		"This mod is so awesome, but it's a real downer there's no quest version.",
		"Frick, I really wanted to play this mod on my Oculus, but no quest version makes it impossible.",
		"ugh wtf why ther no quest vrison fr this mod? this is just frickin annoyin.",
		"serioulsy why do they not mak a quest vrison for this mod, it's like they dont care or somthing.",
		"i cant bleve this mod has no quest vrison, what is this poop?",
		"poop, i wanted to play this mod on my Oculus but no quest vrison? r u kiddin me?",
		"this mod is so gud, but i cant play it on my Oculus coz theres no quest vrison. fml.",
		"y do they mak such an awsome mod but not make it vr compatible? im so pissed.",
		"come on, this mod needs a quest vrison, its so annoying that it doesnt hav one.",
		"frick, this mod wuld be so much better if it had a quest vrison. i dont understand why they didnt make one.",
		"seriously, it's like they dont care about Oculus players coz they dont hav a quest vrison for this mod.",
		"ugh, this mod is poop without a quest vrison. i cant play it on my Oculus, and its so frustrating.",
		"are you kidding me? this mod doesn't have a quest vrison, what kind of bs is this?",
		"im so done with mods that dont have quest vrison, it's like they're stuck in the past or somthing.",
		"this mod is so gud, but without a quest vrison, its just incomplete. its such a letdown.",
		"i cant bleve this, i was really lookin forward to playin this mod on my Oculus, but no quest vrison? frickin ridiculous.",
		"seriously, the devs need to get their shit together and make a quest vrison for this mod. it's not that hard.",
		"frick, i dont wanna play this mod on my pc, i wanna play it on my Oculus, but no quest vrison means nothin doin.",
		"this mod is poop without a quest vrison. im so frustrated right now.",
		"come on, its 2023, vr is the future, why doesnt this mod have a quest vrison yet?",
		"if this mod had a quest vrison, it would be the best mod ever. but no, they had to screw it up.",
		"what kind of devs dont make a quest vrison for their mod? its so unprofessional and frustrating.",
		"i cant believe i wasted money on this mod, only to find out there's no quest vrison. im so annoyed.",
		"why do they bother making a mod if they're not gonna make it compatible with vr? it's just frickin dumb.",
		"frick, i hate when mods dont have quest vrison, it's like they're tryna exclude vr players or somthing.",
		"this mod is such a tease, it looks amazing, but without a quest vrison, its just a big letdown.",
		"ugh, i dont even wanna play this mod now that i know theres no quest vrison. its just not worth it.",
		"why dont they care about Oculus players? why no quest vrison? it's like they're tryna piss us off.",
		"this mod is missing something crucial, a quest vrison. without it, its just a waste of time.",
		"i wish devs wuld stop neglecting vr players and make quest vrison for their mods. it's not that hard.",
		"seriously, why do i even bother with mods that dont have quest vrison? it's just a waste of money and time.",
		"poop, i was really excited for this mod, but no quest vrison means i cant play it on my Oculus. im so mad.",
		"what's the point of making a mod if it doesnt hav quest vrison? it just doesnt make sense.",
		"this mod is so gud, but without a quest vrison, its just a frickin tease. im so frustrated.",
		"i cant bleve im still finding mods that dont have quest vrison in 2023. its just ridiculous.",
		"frick, i hate it when mods dont hav quest vrison, it's like they're tryna exclude us vr players.",
		"without a quest vrison, this mod is just a joke. im so annoyed right now.",
		"why cant devs just make quest vrison for their mods? its not like they're doin us a favor or somthing.",
		"seriously, im so tired of finding mods that dont have quest vrison. it's just ridiculous.",
		"i would love to play this mod on my Oculus, but no quest vrison means nothin doin. im so pissed.",
		"this mod is such a disappointment without a quest vrison. i was really lookin foward to playing theis mod but you ar too stupuid to make quest verion.",
		#endregion */
		
		// you should know this guy, or else i'm killing you
		#region bruno powroznik
		"OBJECTS IVE SHOVED UP MY ARSE",
		"I REALLY HATE SIMON FUCKING COWELL",
		"PEOPLE I DONT REALLY LIKE\nYOU\nMYSELF\nSIMON FUCKING COWELL",
		"THE TWAT",
		"PENS",
		"PENCILS",
		"COINS",
		"PEBBLES",
		"BROOMSTICK HANDLE",
		"FISHING ROD HANDLE",
		"VIBRATORS",
		"MARGARET THATCHER IS DEAD",
		"DING DONG THE WICKED BITCH IS DEAD",
		"ITS A SHAME THE BITCH DIDNT DIE 87 YEARS AGO",
		#endregion
		
		// Ham.
		#region dingus
		"They shot our face, Johnny! THEY SHOT OUR FACE!",
		"Who up tugging they gooch",
		"rabbit — 01/01/2024 4:24 AM\nPrepare ur. Grave.  [EXTREMELYLOUDINCORRECTBUZZER]",
		"I got a big AR this’ll turn you to piss",
		"Trailer 1\nTuesday, December 5th\n9AM ET",
		"YSL cologne bitch, this not Axe",
		#endregion
		
		// i let him type on my keyboard
		#region my cat
		"bn g",
		"gf",
		".n",
		"etjrh"
		#endregion
	};
	
	private readonly List<string> _usedItems = new();
		
	public string GetString()
	{
		if (_items.Count == 0)
		{
			if (_usedItems.Count == 0)
			{
				MelonLogger.Error("Somehow, both lists are empty.");
			}
			_items.AddRange(_usedItems);
			_usedItems.Clear();
		}
		var rand = new Random();
		var randomIndex = rand.Next(0, _items.Count);
		var selectedItem = _items[randomIndex];
		_items.RemoveAt(randomIndex);
		_usedItems.Add(selectedItem);
		return selectedItem;
	}
}